[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
# decorations = "none"
opacity = 0.97

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[font]
size = 14
normal = { family = "Cascadia Mono", style = "Regular" }
bold = { family = "Cascadia Mono", style = "Bold" }
italic = { family = "Cascadia Mono", style = "Italic" }
