#!/bin/bash
# cool stuff bucko
export PS1="λ \w: "
export LC_ALL="C.UTF8"
export LANG="C.UTF8"

export GOPATH="$HOME/go"

export HISTSIZE=1000000
export HISEFILESIZE=1000000
# Avoid duplicates
HISTCONTROL=ignoredups:erasedups
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend

# After each command, append to the history file and reread it
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

if [ -f "$HOME/.tokens" ]; then
  source $HOME/.tokens
fi

export JULIA_STACKTRACE_MINIMAL=true

export EDITOR=nvim

alias j='julialauncher'
alias jn='julialauncher +dev'
alias ..='cd ..'
if command -v nvim > /dev/null; then
   alias vim='nvim'
   alias vi='nvim'
   alias v='nvim'
fi
alias gst='git status'
alias ga='git add'
alias gc='git commit'
alias md='mkdir -p'
alias gp='git push'
alias sudo2='sudo -E env "PATH=$PATH"'
if command -v bat > /dev/null; then
   alias cat='bat'
fi
if command -v python3.11 > /dev/null; then
   alias python3='python3.11'
   alias py='python3.11'
fi
# alias python='python3'
alias ipy='ipython'
# alias jfmt='julia --startup=no -e "using JuliaFormatter; format(\".\")"'
jfmt () {
   local dir=${1:-.}
   julia --startup=no -t auto -e "using JuliaFormatter; format(\"$dir\")"
}

export FZF_DEFAULT_OPTS='--height 80% --reverse --inline-info'
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude '{.git,.mypy_cache,node_modules,vendor}/'"

bind -x '"\C-p": nvim $(fzf);'

# INITIAL_QUERY=""
# RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
# # FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
# bind -x '"\C-r": fzf --bind "change:reload:$RG_PREFIX {q} || true" \
#       --ansi --query "$INITIAL_QUERY" \
#       --height=50% --layout=reverse'

tm() {
   [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
   if [ $1 ]; then
      tmux $change -t "$1" 2>/dev/null || (tmux new-session -d -s $1 && tmux $change -t "$1"); return
   fi
   session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0) &&  tmux $change -t "$session" || echo "No sessions found."
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval "$(zoxide init bash)"

export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH

export GO111MODULE=on
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"

export PATH="$HOME/.deno/bin:$PATH"

if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then . $HOME/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# easy place to put manually downloaded binaries
export PATH="$HOME/bin:$PATH"

function gcob() {
   git branch | grep --invert-match '\*' | cut -c 3- |
      fzf --multi --preview="git log {}" |
      xargs --no-run-if-empty git checkout
}

# rust
. "$HOME/.cargo/env"

export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/key-bindings.bash"
  source "$(fzf-share)/completion.bash"
fi

RG() {
  RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
  INITIAL_QUERY="$1"
  local selected=$(
    FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY' || true" \
      fzf --bind "change:reload:$RG_PREFIX {q} || true" \
          --ansi --disabled --query "$INITIAL_QUERY" \
          --delimiter : \
          --preview 'bat --style=full --color=always --highlight-line {2} {1}' \
          --preview-window '~3:+{2}+3/2'
  )
  [ -n "$selected" ] && $EDITOR "$selected"
}

command -v bat  > /dev/null && export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always {}'"

is_in_git_repo() {
  git rev-parse HEAD > /dev/null 2>&1
}

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in *:/home/dom/.juliaup/bin:*);; *)
    export PATH=/home/dom/.juliaup/bin${PATH:+:${PATH}};;
esac

# <<< juliaup initialize <<<

# avm (Anchor)
export PATH="/home/dom/.avm/bin:$PATH"

export PATH="$PATH:/home/dom/.foundry/bin"

export FLYCTL_INSTALL="/home/dom/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

BUN_INSTALL="/home/dom/.bun"
PATH="$BUN_INSTALL/bin:$PATH"

export PATH="$HOME/nvim-linux64/bin:$PATH"

eval "$(direnv hook bash)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Wasmer
export WASMER_DIR="/home/dom/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"

# add ziglang to path
export PATH="$PATH:/home/dom/ziglang"

export WASMTIME_HOME="$HOME/.wasmtime"

export PATH="$WASMTIME_HOME/bin:$PATH"

export PATH="$HOME/.local/bin:$PATH"

# export PYENV_ROOT="$HOME/.pyenv"
# command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/dom/google-cloud-sdk/path.bash.inc' ]; then . '/home/dom/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/dom/google-cloud-sdk/completion.bash.inc' ]; then . '/home/dom/google-cloud-sdk/completion.bash.inc'; fi

# Enable programmable completion features
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Custom directory cycling completion with contents display
_cycle_dirs_with_contents() {
    local cur prev dir_prefix dirs
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    dir_prefix="$1"

    if [[ ${prev} == cd ]]; then
        dirs=$(find . -maxdepth 1 -type d -name "${cur}*" -exec basename {} \; 2>/dev/null)
        COMPREPLY=( $(compgen -W "${dirs}" -- ${cur}) )

        return 0
    fi
}

complete -F _cycle_dirs_with_contents cd

# Change the behavior of the Tab key to cycle through the available options
bind 'TAB:menu-complete'

# Custom cd with fzf integration using fd
function cdf() {
  local dir
  dir=$(fd --type d --max-depth 3 --hidden --exclude '{.git,.mypy_cache,node_modules,vendor,__pycache__,.ipynb_checkpoints}/' . | fzf --preview 'ls -lah --color=always {}' --preview-window=up:50%:wrap)
  if [[ -n "$dir" ]]; then
    cd "$dir" || return 1
  fi
}

# Tab completion for custom cd
complete -C 'compgen -A directory' cdf

# Custom ... function to navigate upwards with fzf using fd
function ...() {
  local dir
  dir=$(fd --type d --max-depth 1 --hidden --exclude '{.git,.mypy_cache,node_modules,vendor,__pycache__,.ipynb_checkpoints}/' --search-path .. | fzf --preview 'ls -lah --color=always {}' --preview-window=up:50%:wrap)
  if [[ -n "$dir" ]]; then
    cd "$dir" || return 1
  fi
}

###-begin-neonctl-completions-###
#
# yargs command completion script
#
# Installation: neonctl completion >> ~/.bashrc
#    or neonctl completion >> ~/.bash_profile on OSX.
#
_neonctl_yargs_completions()
{
    local cur_word args type_list

    cur_word="${COMP_WORDS[COMP_CWORD]}"
    args=("${COMP_WORDS[@]}")

    # ask yargs to generate completions.
    type_list=$(neonctl --get-yargs-completions "${args[@]}")

    COMPREPLY=( $(compgen -W "${type_list}" -- ${cur_word}) )

    # if no match was found, fall back to filename completion
    if [ ${#COMPREPLY[@]} -eq 0 ]; then
      COMPREPLY=()
    fi

    return 0
}
complete -o bashdefault -o default -F _neonctl_yargs_completions neonctl
###-end-neonctl-completions-###
